name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14

      - run: bun --version

      - run: bun install --frozen-lockfile

      - run: bunx biome --version

      - run: bun run biome:ci

      - run: bun run check
